name: Security Scan with SARIF

on: [push]

jobs:
  security_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-web-app .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-web-app:latest'
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Set up Python and Install Semgrep
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install semgrep

      - name: Run Semgrep Scan (HTML) and Generate SARIF with Local Rules
        run: semgrep --sarif --output semgrep.sarif --config html-rules.yaml ./index.html

      - name: Upload Semgrep SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif